- name: CentOS dirctory are copied
  file: path=/etc/docker state=directory mode=0755
  ignore_errors: yes
  tags: [docker]

- name: CentOS files are copied
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ centos_files }}"
  tags: [docker]

   
- name: add repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    enabled: 1
    gpgcheck: 1
  ignore_errors: yes
  tags: [docker]

- name: CentOS package is installed
  yum:
    name: docker-engine
    state: present
  tags: [docker]

- name: python-pip is present
  yum:
    name: python-pip
    state: present
  tags: [docker]

- name: docker-py is present
  pip:
    name: docker-py
    version: 1.10.6
    state: present
  tags: [docker]

- name: CentOS files are present
  template:
    src: "{{ centos_docker_cfg }}"
    dest: "{{ centos_docker_cfg_dest }}"
  register: copy_result
  tags: [docker]

- name: Centos Daemon is reloaded
  command: systemctl daemon-reload
  when: copy_result|changed and is_systemd is defined
  tags: [docker]

- name: vagrant user is added to the docker group
  user:
    name: vagrant
    group: docker
  register: user_result
  tags: [docker]

- name: Centos Docker service is restarted
  service:
    name: docker
    state: restarted
  when: copy_result|changed or user_result|changed
  tags: [docker]

- name: DockerUI is running
  docker:
    image: uifd/ui-for-docker
    name: dockerui
    ports: 9000:9000
    privileged: yes
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  when: not skip_ui is defined
  ignore_errors: yes
  tags: [docker]

- name: CentOS service is running
  service:
    name: docker
    state: running
  tags: [docker]
